name: Check
on: pull_request
jobs:
  breaking-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.19.0"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=proto"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.19.0"
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
